// import type { Metadata } from "next";
import { Inter, Poppins, Roboto } from "next/font/google";
import React from "react";
import "./globals.css";
import NavBar from "@/components/NavBar";
import type { Metadata } from "next";

{
  /* Import the font*/
}
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["cyrillic"], weight: "300" });
const poppins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Next JS Project",
  description: "First project with NextJS and Tailwind",
  keywords: "tailwind, nextjs, project",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar />
        <main className="py-[10px] px-[40px]">
          {children} {/*content of pages*/}
        </main>
      </body>
    </html>
  );
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
